language: ruby
rvm:
- 2.3.5
deploy:
  provider: heroku
  api_key:
    secure: JgCuEuZufjh0Id6/HJ9dD71VVthuUZ3vY4wxlXb+VTdWNUQZkVn37+ErlRj0CHnCq6N1SxVJb02SRS93PBp9zQHJ0czFLjHrYIlGuyF2ZCiuMJLR6SDKqYqzgzPbHQdLCZBeUbCFlNWaKpv8ReyCl1gqdijyIa8I4fNMA6XNiHG1Apt8FYOjs1O8NZITrrtRE+VPAmwhCKlpflTTExEFvDRKjswJGS85VWdIyXm9HB8Yd5UDfpih96m5t+DQo1PR2DU4qE2cyBrXVXTSg/l1L4lvBG2K4z2JRFp/l0XfVQU+lEUQiWjrmQud1yy+wtBk+UKmZ+sgnP/hXzSSWzy0GflVoSqP22hJRisbxxs1YIuH7+viQ62r99scu0oLYXCDNEo36VTkuAj8WaW/KyG9cALKNszivlDwCG8Il732CiOpF/X8AJlQIXOvFVM4eoBiKTDuY5V16o3vN0zZ6sergTrBaale/JAhJ+9+lRDwVnyqP7OwpXaCOQ8AA0bPYQ3mSGiu5nxvgnwGChmD31VD+1fgwaOP7LG5EMNMK+g1akJP55SR4sBVrFCCrfNjZs2f/HmpNuAtYm2QgtaxClhaEDY8SPnHJ+BHqQneM+LtK33hHJTeChbOdR/3GHBVSpb5o7atlvMM9AHfgjqVKWZgERx+5bmlPbvWIkQUnB2m1o4=
  app: projet-lpa2-tvet
  on:
    repo: trivetroff/projet
  run: rake db:migrate
before_script:
- psql -c 'create database db_test;' -U postgres
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
after_script:
- "./cc-test-reporter format-coverage -t simplecov"
- if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage; fi
env:
  global:
    secure: AbxjgwhIzgiBmRyXZzQdCWYSNgvs6pf+X2lB5FvDFcL4LMRoj5Pnmh/8xfrs2GKQ1zSHAIeLvI+YlOhNH+VY5gMzHJqgPFFjbvudnwox2027qLf6hamf1mDUVQDTMjalPmMjxkFjqfb/auyQVCfyAMaH86wQ4oHcc2i566gIJwXmYzQ7p5TtCYfEAvqXhSTyY2/PcN/sussAoJoXyIHjJe+O5juAdXaB0DqNcZSpeBWQ3hrlHDo97Lx/hnPs7KJotyGcipWq4Ez0PhAtKt54j31LXW08M6917kXS4WMcQ3z+MkmAN4ai/U18zKULUjpWUSsJTgQT1is0CKcr2KYztuc16+seNzwdPCquJvsfe/x17q0QkAIfGevM5ao41nrIIQi68weQ527G5aHwOUVyFAp45cwErkejWFrZUIJEfhCHYbplUmNL+CZstr7X1yf+RK9L//+KHRGLlAZqZhAmp8sQzAoLrlSt4vu68FVwNZfsZgz1H95D+yR/p+V1sqgDG06ZeX7nZHsGWhgDEQqiTxMCb7UV2/Zvz3SRXcU5YxPDFmZud0xczgDl18lo4GOVvLCHx5Ej6UZG/ZGwSc6169BxileXpYK97vnxW42yBfjDIW5ZBSaVAFBQwxmZ9OLvM0GjuOj0dINzj91+1nt69yNykdDfuBeJpTxmLaZ+vrI=
