# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1495d4fa62dae00957739c8cd7e9840a2941e4df1a04923c763c54ecbdf2b459ea13a14907fd926428e2b63d4aef388e153056c431d44a23f560018c125f36d2

test:
  secret_key_base: 47b300299c54a6639fa98b6a70baadbe43485f619d176eb4bb469bf7f39d1bf9b1725f1cb5910c332392aec40d79ca1e4fba6ff78faab05b3e8b5c4f75c25c9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
